/**
 * Static catalog of every proposal type the DeXe frontend exposes. Derived
 * from a full audit of `C:/dev/investing-dashboard` forms + hooks
 * (2026-04-15). Consumed by `dexe_proposal_catalog` so agents can discover
 * which builder tool to call for a given user intent.
 *
 * `mcpTool` is the name of the dedicated MCP builder tool (when one exists)
 * or `null` if agents must compose via primitives (`build_external` +
 * `build_custom_abi`) — flip `implemented` to `true` as each ships.
 */
export type ProposalCategory = "external" | "internal" | "offchain";

export interface ProposalTypeEntry {
  id: string;
  category: ProposalCategory;
  name: string;
  formPath: string;
  /** High-level description of the on-chain effect or off-chain action. */
  effect: string;
  /** Target contract (on-chain) or backend endpoint (off-chain). */
  target: string;
  /** Does this type require an IPFS metadata upload? */
  needsIpfs: boolean;
  /** Gating tags: "expert", "validator", "babt", "dao-admin". */
  gating: string[];
  /** Dedicated MCP builder tool name, or null. */
  mcpTool: string | null;
  /** Shipped? */
  implemented: boolean;
}

export const PROPOSAL_CATALOG: ProposalTypeEntry[] = [
  // ---------- External (on-chain, call GovPool.createProposal, needs IPFS) ----------
  {
    id: "external.modify_dao_profile",
    category: "external",
    name: "Modify DAO Profile",
    formPath: "src/forms/createProposal/external/ModifyDaoProfileForm",
    effect: "Update DAO descriptionURL pointer",
    target: "GovPool.editDescriptionURL(string)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_modify_dao_profile",
    implemented: true,
  },
  {
    id: "external.change_voting_settings",
    category: "external",
    name: "Change Voting Settings",
    formPath: "src/forms/createProposal/external/ChangeVotingSettingsForm",
    effect: "Add or edit ProposalSettings on GovSettings (quorum, duration, etc.)",
    target: "GovSettings.addSettings / editSettings (encoded as actionsOnFor)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_change_voting_settings",
    implemented: true,
  },
  {
    id: "external.token_distribution",
    category: "external",
    name: "Token Distribution",
    formPath: "src/forms/createProposal/external/TokenDistributionForm",
    effect: "Distribute tokens via DistributionProposal.execute(proposalId, token, amount)",
    target: "DistributionProposal.execute(uint256,address,uint256)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_token_distribution",
    implemented: true,
  },
  {
    id: "external.token_sale",
    category: "external",
    name: "Token Sale (create tier)",
    formPath: "src/forms/createProposal/external/TokenSaleForm",
    effect: "Launch a new token sale tier",
    target: "TokenSaleProposal.createTiers(ITier[])",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_token_sale",
    implemented: true,
  },
  {
    id: "external.token_transfer",
    category: "external",
    name: "Token Transfer (treasury → address)",
    formPath: "src/forms/createProposal/external/TokenTransferForm",
    effect: "Transfer ERC20 from DAO treasury to a single recipient",
    target: "ERC20.transfer (as actionsOnFor on the token contract)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_token_transfer",
    implemented: true,
  },
  {
    id: "external.token_sale_recover",
    category: "external",
    name: "Recover Token Sale",
    formPath: "src/forms/createProposal/external/TokenSaleRecoverForm",
    effect: "Recover unsold tokens from tiers",
    target: "TokenSaleProposal.recover(uint256[] tierIds)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_token_sale_recover",
    implemented: true,
  },
  {
    id: "external.withdraw_treasury",
    category: "external",
    name: "Withdraw from Treasury",
    formPath: "src/forms/createProposal/external/WithdrawForm",
    effect: "Withdraw native or ERC20 from DAO treasury",
    target: "GovPool.withdraw(receiver, amount, nftIds) — treasury lives on GovPool itself",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_withdraw_treasury",
    implemented: true,
  },
  {
    id: "external.manage_validators",
    category: "external",
    name: "Manage Validators (add/remove/balance)",
    formPath: "src/forms/createProposal/external/ManageValidatorsForm",
    effect: "Direct call to GovValidators.changeBalances(balances, users). Set balance=0 to remove.",
    target: "GovValidators.changeBalances(uint256[], address[])",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_manage_validators",
    implemented: true,
  },
  {
    id: "external.delegate_tokens_to_expert",
    category: "external",
    name: "Delegate Tokens to Expert",
    formPath: "src/forms/createProposal/external/DelegateOrRevokeTokensForm",
    effect: "Delegate DAO treasury tokens/NFTs to an expert address",
    target: "GovPool.delegateTreasury(delegatee, amount, nftIds)",
    needsIpfs: true,
    gating: ["expert"],
    mcpTool: "dexe_proposal_build_delegate_to_expert",
    implemented: true,
  },
  {
    id: "external.revoke_tokens_from_expert",
    category: "external",
    name: "Revoke Tokens from Expert",
    formPath: "src/forms/createProposal/external/DelegateOrRevokeTokensForm",
    effect: "Undelegate treasury tokens/NFTs from an expert",
    target: "GovPool.undelegateTreasury(delegatee, amount, nftIds)",
    needsIpfs: true,
    gating: ["expert"],
    mcpTool: "dexe_proposal_build_revoke_from_expert",
    implemented: true,
  },
  {
    id: "external.validators_allocation",
    category: "external",
    name: "Validators Allocation",
    formPath: "src/forms/createProposal/external/ValidatorsAllocationForm",
    effect: "Reallocate validator stake weights (use manage_validators wrapper)",
    target: "GovValidators.changeBalances",
    needsIpfs: true,
    gating: ["validator"],
    mcpTool: "dexe_proposal_build_manage_validators",
    implemented: true,
  },
  {
    id: "external.add_local_expert",
    category: "external",
    name: "Add Local Expert",
    formPath: "src/forms/createProposal/external/ExpertApplicationForm",
    effect: "Grant local-expert role to an address (mint ExpertNft)",
    target: "ExpertNft.mint(address, uri) — scope='local'",
    needsIpfs: true,
    gating: ["expert"],
    mcpTool: "dexe_proposal_build_add_expert",
    implemented: true,
  },
  {
    id: "external.add_global_expert",
    category: "external",
    name: "Add Global Expert",
    formPath: "src/forms/createProposal/external/ExpertApplicationForm",
    effect: "Grant global-expert role (DeXe-wide)",
    target: "DeXeExpertNft.mint(address, uri) — scope='global'",
    needsIpfs: true,
    gating: ["expert"],
    mcpTool: "dexe_proposal_build_add_expert",
    implemented: true,
  },
  {
    id: "external.remove_local_expert",
    category: "external",
    name: "Remove Local Expert",
    formPath: "src/forms/createProposal/external/ExpertRemovalForm",
    effect: "Revoke local-expert role (burn ExpertNft)",
    target: "ExpertNft.burn(address) — scope='local'",
    needsIpfs: true,
    gating: ["expert"],
    mcpTool: "dexe_proposal_build_remove_expert",
    implemented: true,
  },
  {
    id: "external.remove_global_expert",
    category: "external",
    name: "Remove Global Expert",
    formPath: "src/forms/createProposal/external/ExpertRemovalForm",
    effect: "Revoke global-expert role (burn DeXeExpertNft)",
    target: "DeXeExpertNft.burn(address) — scope='global'",
    needsIpfs: true,
    gating: ["expert"],
    mcpTool: "dexe_proposal_build_remove_expert",
    implemented: true,
  },
  {
    id: "external.reward_multiplier",
    category: "external",
    name: "Reward Multiplier (set address / set URI / mint)",
    formPath: "src/forms/createProposal/external/RewardMultiplierForm",
    effect: "Manage reward-multiplier NFT (3 modes)",
    target: "GovPool.setNftMultiplierAddress / ERC721Multiplier.setURI / .mint",
    needsIpfs: true,
    gating: ["expert"],
    mcpTool: "dexe_proposal_build_reward_multiplier",
    implemented: true,
  },
  {
    id: "external.apply_to_dao",
    category: "external",
    name: "Apply to DAO",
    formPath: "src/forms/createProposal/external/ApplyToDaoForm",
    effect: "Grant tokens from DAO treasury (transfer + optional mint for shortfall)",
    target: "ERC20.transfer [+ ERC20Gov.mint if needed]",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_apply_to_dao",
    implemented: true,
  },
  {
    id: "external.blacklist",
    category: "external",
    name: "Blacklist Management",
    formPath: "src/forms/createProposal/external/BlacklistManagementForm",
    effect: "Add/remove addresses from ERC20Gov blacklist (1-2 actions)",
    target: "ERC20Gov.blacklist(address[], bool)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_blacklist",
    implemented: true,
  },
  {
    id: "external.custom_abi",
    category: "external",
    name: "Arbitrary Contract Call (ABI)",
    formPath: "src/forms/createProposal/external/AbiForm",
    effect: "User supplies target + method + args; we ABI-encode",
    target: "Any contract (user-specified)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_custom_abi",
    implemented: true,
  },
  {
    id: "external.manual_calldata",
    category: "external",
    name: "Manual Calldata Entry",
    formPath: "src/forms/createProposal/external/ManualForm",
    effect: "Raw {target, callData, value}[] — no encoding",
    target: "Any",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_external",
    implemented: true,
  },
  {
    id: "external.new_proposal_type",
    category: "external",
    name: "Create Custom Proposal Type (settings template)",
    formPath: "src/forms/createProposal/external/NewProposalTypeForm",
    effect: "Register new ProposalSettings + executor binding (2 actions)",
    target: "GovSettings.addSettings + GovSettings.changeExecutors",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_new_proposal_type",
    implemented: true,
  },
  {
    id: "external.change_math_model",
    category: "external",
    name: "Change Proposal Math Model",
    formPath: "src/forms/createProposal/external/ChangeMathModelForm",
    effect: "Swap voting-power math contract (linear / polynomial / custom)",
    target: "GovPool.changeVotePower(address)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_change_math_model",
    implemented: true,
  },
  {
    id: "external.enable_staking",
    category: "external",
    name: "Enable Staking",
    formPath: "src/forms/createProposal/external/EnableStakingForm",
    effect: "Frontend routes this via `new_proposal_type` — register settings + bind StakingProposal executor",
    target: "GovSettings.addSettings + changeExecutors (via new_proposal_type)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_new_proposal_type",
    implemented: true,
  },
  {
    id: "external.create_staking_tier",
    category: "external",
    name: "Create Staking",
    formPath: "src/forms/createProposal/external/CreateStakingTierForm",
    effect: "Create a staking pool (reward token + duration)",
    target: "StakingProposal.createStaking(address,uint256,uint256,uint256,string)",
    needsIpfs: true,
    gating: [],
    mcpTool: "dexe_proposal_build_create_staking_tier",
    implemented: true,
  },

  // ---------- Internal (GovValidators.createInternalProposal) ----------
  {
    id: "internal.change_validator_balances",
    category: "internal",
    name: "Change Validator Balances",
    formPath: "src/forms/createProposal/internal/ManageValidatorsForm",
    effect: "Directly change validator stake amounts (type 0). Set balance=0 to remove.",
    target: "GovValidators.createInternalProposal(type=0, url, data) — data=changeBalances(balances,users)",
    needsIpfs: true,
    gating: ["validator"],
    mcpTool: "dexe_proposal_build_change_validator_balances",
    implemented: true,
  },
  {
    id: "internal.change_validator_settings",
    category: "internal",
    name: "Change Validator Settings",
    formPath: "src/forms/createProposal/internal/ChangeVotingSettingsForm",
    effect: "Change validator voting duration / executionDelay / quorum (type 1)",
    target: "GovValidators.createInternalProposal(type=1, url, data) — data=changeSettings(duration,executionDelay,quorum)",
    needsIpfs: true,
    gating: ["validator"],
    mcpTool: "dexe_proposal_build_change_validator_settings",
    implemented: true,
  },
  {
    id: "internal.monthly_withdraw",
    category: "internal",
    name: "Monthly Validator Withdraw",
    formPath: "src/forms/createProposal/internal/MonthlyWithdrawForm",
    effect: "Pay validators from treasury (multi-token supported) (type 2)",
    target: "GovValidators.createInternalProposal(type=2, url, data) — data=monthlyWithdraw(tokens[],amounts[],destination)",
    needsIpfs: true,
    gating: ["validator"],
    mcpTool: "dexe_proposal_build_monthly_withdraw",
    implemented: true,
  },
  {
    id: "internal.offchain_proposal",
    category: "internal",
    name: "Off-chain Internal Proposal (validators vote on off-chain result)",
    formPath: "src/forms/createProposal/internal/EmptyTxForm",
    effect: "Validators vote to attest an off-chain result (type 3, empty data bytes)",
    target: "GovValidators.createInternalProposal(type=3, url, 0x)",
    needsIpfs: true,
    gating: ["validator"],
    mcpTool: "dexe_proposal_build_offchain_internal_proposal",
    implemented: true,
  },

  // ---------- Off-chain (DeXe backend API, no on-chain tx) ----------
  {
    id: "offchain.single_option",
    category: "offchain",
    name: "Single-option Off-chain Voting",
    formPath: "src/forms/createProposal/offchain/TypedProposaForm",
    effect: "Pick one of N options, tallied off-chain",
    target: "POST /integrations/voting/proposals (voting_type=one_of)",
    needsIpfs: false,
    gating: [],
    mcpTool: "dexe_proposal_build_offchain_single_option",
    implemented: true,
  },
  {
    id: "offchain.multi_option",
    category: "offchain",
    name: "Multi-option Off-chain Voting",
    formPath: "src/forms/createProposal/offchain/TypedProposaForm",
    effect: "Pick any subset of N options",
    target: "POST /integrations/voting/proposals (voting_type=multiple_of)",
    needsIpfs: false,
    gating: [],
    mcpTool: "dexe_proposal_build_offchain_multi_option",
    implemented: true,
  },
  {
    id: "offchain.for_against",
    category: "offchain",
    name: "For/Against Off-chain Voting",
    formPath: "src/forms/createProposal/offchain/TypedProposaForm",
    effect: "Binary vote (default labels: For / Against)",
    target: "POST /integrations/voting/proposals (voting_type=for_against)",
    needsIpfs: false,
    gating: [],
    mcpTool: "dexe_proposal_build_offchain_for_against",
    implemented: true,
  },
  {
    id: "offchain.change_voting_settings",
    category: "offchain",
    name: "Change Off-chain Voting Settings",
    formPath: "src/forms/createProposal/offchain/ChangeVotingSettingsForm",
    effect: "Update DAO-wide off-chain voting parameters",
    target: "POST /integrations/voting/proposals (attributes.type=edit_proposal_type)",
    needsIpfs: false,
    gating: [],
    mcpTool: "dexe_proposal_build_offchain_settings",
    implemented: true,
  },
  {
    id: "offchain.new_template",
    category: "offchain",
    name: "Save Voting Template",
    formPath: "src/forms/createProposal/offchain/NewTemplateForm",
    effect: "Persist a reusable voting-template record",
    target: "POST /integrations/voting/proposals (attributes.type=create_proposal_type)",
    needsIpfs: false,
    gating: [],
    mcpTool: "dexe_proposal_build_offchain_settings",
    implemented: true,
  },
];

/** Metadata JSON shape used by the frontend for every external proposal. */
export const EXTERNAL_METADATA_SHAPE = {
  proposalName: "string (required)",
  proposalDescription: "string (required, markdown/slate)",
  category: "string (e.g. 'Token Transfer', 'Manage Validators')",
  isMeta: "boolean (default false)",
  changes: "object (type-specific structured payload for indexing, optional)",
} as const;

export const INTERNAL_METADATA_SHAPE = {
  proposalName: "string (required)",
  proposalDescription: "string",
  category: "string (ValidatorBalances | ValidatorSettings | MonthlyWithdraw | Offchain)",
  changes: "object (type-specific)",
} as const;
